export const config = {
  api: {
    bodyParser: {
      sizeLimit: '20mb'
    }
  },
  maxDuration: 60
}

// Image generation models in order of preference
const IMAGE_MODELS = [
  'gemini-2.5-flash-image',
  'gemini-3.1-flash-image-preview',
  'gemini-3-pro-image-preview',
]

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey) {
    return res.status(500).json({ error: 'API key not configured' })
  }

  try {
    const { prompt, sketchImages, refImages } = req.body

    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' })
    }

    // Build content parts: sketch images first, then reference images, then prompt
    const parts = []

    if (sketchImages && sketchImages.length > 0) {
      for (const img of sketchImages) {
        parts.push({
          inlineData: { mimeType: img.mimeType, data: img.data }
        })
      }
    }

    if (refImages && refImages.length > 0) {
      for (const img of refImages) {
        parts.push({
          inlineData: { mimeType: img.mimeType, data: img.data }
        })
      }
    }

    parts.push({ text: prompt })

    let lastError = ''

    // Try each image model until one works
    for (const model of IMAGE_MODELS) {
      console.log(`[render] Trying model: ${model}`)

      try {
        const controller = new AbortController()
        const timeoutId = setTimeout(() => controller.abort(), 55000) // 55s timeout (Vercel max is 60s)

        const response = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            signal: controller.signal,
            body: JSON.stringify({
              contents: [{ parts }],
              generationConfig: {
                responseModalities: ['TEXT', 'IMAGE'],
              }
            }),
          }
        )
        clearTimeout(timeoutId)

        if (!response.ok) {
          const errData = await response.json().catch(() => ({}))
          lastError = errData.error?.message || `API error: ${response.status}`
          console.error(`[render] Error ${response.status} for ${model}:`, lastError)

          // If overloaded, try next model
          if (response.status === 503 || response.status === 429) {
            continue
          }
          return res.status(response.status).json({ error: lastError })
        }

        const data = await response.json()

        // Extract images and text from response
        const responseParts = data.candidates?.[0]?.content?.parts || []
        const images = []
        let text = ''

        for (const part of responseParts) {
          if (part.inlineData) {
            images.push({
              mimeType: part.inlineData.mimeType,
              data: part.inlineData.data
            })
          }
          if (part.text) {
            text += part.text
          }
        }

        if (images.length === 0) {
          const finishReason = data.candidates?.[0]?.finishReason
          if (finishReason === 'IMAGE_SAFETY') {
            return res.status(400).json({ error: 'Image was blocked by safety filters. Try a different prompt.' })
          }
          lastError = `No image generated by ${model} (reason: ${finishReason || 'unknown'})`
          console.error(`[render] ${lastError}`)
          continue
        }

        console.log(`[render] Success with ${model}: ${images.length} image(s)`)
        return res.status(200).json({ images, text, model })

      } catch (fetchErr) {
        if (fetchErr.name === 'AbortError') {
          lastError = `${model} timed out`
          console.error(`[render] ${lastError}`)
          continue
        }
        throw fetchErr
      }
    }

    // All models failed
    return res.status(503).json({ error: `All image models failed. Last error: ${lastError}` })

  } catch (error) {
    console.error('[render] Error:', error.message)
    return res.status(500).json({ error: error.message })
  }
}
